CREATE DATABASE DrugStoreApp
use DrugStoreApp
CREATE TABLE Owners (
Id INT PRIMARY KEY IDENTITY(1,1),
[Name] NVARCHAR(50) NOT NULL,
Surname NVARCHAR(50) NOT NULL,
)
CREATE TABLE DrugStores(
Id INT PRIMARY KEY IDENTITY(1,1),
[Name] NVARCHAR(50) NOT NULL,
Adress NVARCHAR(50) NOT NULL,
ContactNumber NVARCHAR(50) DEFAULT '+994000000000',
CreationDate DATETIME DEFAULT GETDATE() CHECK (CreationDate <= GETDATE()),
OwnerId INT FOREIGN KEY REFERENCES Owners(Id)
)
CREATE TABLE Drugs(
Id INT PRIMARY KEY IDENTITY(1,1),
[Name] NVARCHAR(50) NOT NULL,
Price DECIMAL(5,2),
[Count] INT DEFAULT 0,
DrugStoreId INT FOREIGN KEY REFERENCES DrugStores(Id),
)
CREATE TABLE Druggists(
Id INT PRIMARY KEY IDENTITY(1,1),
[Name] NVARCHAR(50) NOT NULL,
Surname NVARCHAR(50) NOT NULL,
BirthDate DATE,
DrugStoreId INT FOREIGN KEY REFERENCES DrugStores(Id),
)
INSERT INTO Owners
VALUES ('Nuray','Pashayeva')
INSERT INTO DrugStores
VALUES ('Buta','Xetai','+994107100605','2020-09-27',1)
INSERT INTO Drugs
VALUES ('Majezik',4.5,2,1)
INSERT INTO Druggists
VALUES ('Aysu','Qasimov','2000-12-21',1)
SELECT * FROM Owners
SELECT * FROM DrugStores
SELECT * FROM Drugs
SELECT * FROM Druggists