CREATE DATABASE LibraryManagement
use LibraryManagement
CREATE TABLE Genres(
Id INT PRIMARY KEY IDENTITY(1,1),
[Name] NVARCHAR(50) NOT NULL,
)
CREATE TABLE Books(
Id INT PRIMARY KEY IDENTITY(1,1),
[Name] NVARCHAR(50) NOT NULL,
[Count] INT DEFAULT '0',
GenreId INT FOREIGN KEY REFERENCES Genres(Id),
)
CREATE TABLE Authors(
Id INT PRIMARY KEY IDENTITY(1,1),
[Name] NVARCHAR(50) NOT NULL,
Surname NVARCHAR(70) NOT NULL,
BookId INT FOREIGN KEY REFERENCES Books(Id),
GenreId INT FOREIGN KEY REFERENCES Genres(Id),
)
CREATE TABLE Libraries(
Id INT PRIMARY KEY IDENTITY(1,1),
[Name] NVARCHAR(50) NOT NULL,
Adress NVARCHAR(70) UNIQUE NOT NULL,
BookId INT FOREIGN KEY REFERENCES Books(Id),
GenreId INT FOREIGN KEY REFERENCES Genres(Id),
AuthorId INT FOREIGN KEY REFERENCES Authors(Id),
)
INSERT INTO Genres
VALUES ('Bedii Edebiyyat')
SELECT * FROM Genres
INSERT INTO Books
VALUES ('Sefiller',5,1)
SELECT * FROM Books
INSERT INTO Authors
VALUES ('Victor','Hugo',1,1)
SELECT * FROM Authors
INSERT INTO Libraries
VALUES ('Baku Book Centre','Tarqovi',1,1,1)
SELECT * FROM Libraries
