CREATE DATABASE CodeAcademy
use CodeAcademy
CREATE TABLE GroupTypes(
Id INT PRIMARY KEY IDENTITY(1,1),
[Name] NVARCHAR(50) NOT NULL,
)
CREATE TABLE Topics(
Id INT PRIMARY KEY IDENTITY(1,1),
[Name] NVARCHAR(50) NOT NULL,
LessonHours INT NOT NULL,
GroupTypeId INT FOREIGN KEY REFERENCES GroupTypes(Id),
)
CREATE TABLE Groups(
Id INT PRIMARY KEY IDENTITY(1,1),
[Name] NVARCHAR(50) NOT NULL,
StartDate DATE DEFAULT GETDATE() CHECK (StartDate <= GETDATE()),
EndDate DATE,
LessonHours INT NOT NULL,
GroupTypeId INT FOREIGN KEY REFERENCES GroupTypes(Id),
)
CREATE TABLE Students(
Id INT PRIMARY KEY IDENTITY(1,1),
[Name] NVARCHAR(50) NOT NULL,
Surname NVARCHAR(50) NOT NULL,
BirthDate DATE,
RegistrationDate DATETIME DEFAULT GETDATE() CHECK (RegistrationDate <= GETDATE()),
PhoneNumber NVARCHAR(50) DEFAULT '+994000000000',
Email NVARCHAR(50) UNIQUE NOT NULL,
GroupId INT FOREIGN KEY REFERENCES Groups(Id),
)
CREATE TABLE ExerciseTypes(
Id INT PRIMARY KEY IDENTITY(1,1),
[Name] NVARCHAR(50) NOT NULL,
)
CREATE TABLE Exercises(
Id INT PRIMARY KEY IDENTITY(1,1),
[Name] NVARCHAR(50) NOT NULL,
Grade INT CHECK (Grade<=100) NOT NULL,
ExerciseTypeId INT FOREIGN KEY REFERENCES ExerciseTypes(Id),
TopicId INT FOREIGN KEY REFERENCES Topics(Id),
StudentId INT FOREIGN KEY REFERENCES Students(Id),
)
INSERT INTO GroupTypes
VALUES ('Programming')
SELECT * FROM GroupTypes
INSERT INTO Groups
VALUES ('PB401','2024-03-30','2025-02-12',400,1)
SELECT * FROM Groups
INSERT INTO Topics
VALUES ('SQL',30,1)
SELECT * FROM Topics
INSERT INTO Students
VALUES ('Nuray','Pasahayeva','2006-05-10','2024-01-25','+994107100605','nuray@gmail.com',1)
SELECT * FROM Students
INSERT INTO ExerciseTypes
VALUES ('Quiz')
SELECT * FROM ExerciseTypes
INSERT INTO Exercises
VALUES ('Quiz1',90,1,1,1)
SELECT * FROM Exercises